// Generated by LiveScript 1.2.0
(function(){
  var request, cheerio, fs, mysql, iconv, conn, url, replace$ = ''.replace, join$ = [].join;
  request = require('request');
  cheerio = require('cheerio');
  fs = require('fs');
  mysql = require('mysql');
  iconv = require('iconv-lite');
  conn = mysql.createConnection({
    host: 'localhost',
    user: 'npodata',
    database: 'npodata',
    password: '7tNnc4pXAUWu6tEF'
  });
  url = 'http://donate.mohw.gov.tw/web/';
  request({
    'url': url + 'apply_all_page.asp',
    'encoding': null,
    'method': 'POST',
    'qs': {
      a_date: '1'
    }
  }, function(error, response, body){
    var b, $, rows, j, rows_loop;
    if (!error && response.statusCode === 200) {
      b = iconv.decode(new Buffer(body), "big5");
      $ = cheerio.load(b);
      rows = $('table.text_middle tr');
      j = 0;
      rows_loop = function(){
        return setTimeout(function(){
          var r, a, b, c, d, href, matches, id;
          r = rows[j];
          j++;
          a = $(r).find('td').eq(0);
          b = $(r).find('td').eq(1);
          c = $(r).find('td').eq(2);
          d = $(r).find('td').eq(3);
          href = a.find('a').attr('href');
          matches = /num=(\d+)/.exec(href);
          if (matches != null) {
            id = matches[1];
            conn.query('SELECT id FROM `data` WHERE unix_timestamp(now()) - unix_timestamp(`timestamp`) < 86400*30 AND id = ?', id, function(err, selected){
              var org, title, date, start, end, json;
              if (selected.length < 1) {
                org = b.text();
                title = c.text();
                date = d.text().split('～');
                if (date.length) {
                  start = yearc(date[0]);
                  end = yearc(date[1]);
                  json = {
                    id: id,
                    org: org,
                    title: title,
                    start: start,
                    end: end
                  };
                  return grab_detail(json);
                }
              } else {
                return console.log('skipped ' + id);
              }
            });
          }
          if (j < rows.length) {
            return rows_loop();
          }
        }, 100);
      };
      rows_loop();
    }
    function grab_detail(o){
      var url;
      url = 'http://donate.mohw.gov.tw/web/';
      return request({
        'url': url + 'apply_all.asp',
        'encoding': null,
        'method': 'GET',
        'qs': {
          num: o.id
        }
      }, function(error, response, body){
        var b, $, inner_table, rows, i$, len$, tr, a, c, d, htm, key;
        b = iconv.decode(new Buffer(body), "big5");
        $ = cheerio.load(b);
        inner_table = $('table.text_middle table.text_middle');
        inner_table = '<table>' + inner_table.html() + '</table>';
        $('table.text_middle table.text_middle').remove();
        rows = $('table.text_middle tr');
        for (i$ = 0, len$ = rows.length; i$ < len$; ++i$) {
          tr = rows[i$];
          a = $(tr).find('td').eq(0);
          b = $(tr).find('td').eq(1);
          c = $(tr).find('td').eq(2);
          d = $(tr).find('td').eq(3);
          htm = key = null;
          if (a && b) {
            key = replace$.call(a.text(), /(\r\n|\n|\r|^\s+|\s+$)/gm, '');
            if (key) {
              if (key === '結束備查文件') {
                htm = inner_table;
              } else {
                htm = replace$.call(b.html(), /(\r\n|\n|\r|^\s+|\s+$)/gm, '');
              }
              htm = validate(key, htm);
              if (htm) {
                o[key] = htm;
              }
            }
          }
          if (c && d) {
            key = replace$.call(c.text(), /(\r\n|\n|\r|^\s+|\s+$)/gm, '');
            if (key) {
              htm = replace$.call(d.html(), /(\r\n|\n|\r|^\s+|\s+$)/gm, '');
              htm = validate(key, htm);
              if (htm) {
                o[key] = htm;
              }
            }
          }
        }
        return conn.query('REPLACE INTO data SET?', o, function(err, rows){
          return console.log('inserted ' + o.id);
        });
      });
    }
    function validate(key, htm){
      switch (key) {
      case '申請單位':
        return null;
      case '活動名稱':
        return null;
      case '勸募活動開始':
        return null;
      case '勸募活動結束':
        return null;
      case '所得財物使用年限':
        return yearrange(htm);
      case '賸餘財物再使用年限':
        return yearrange(htm);
      default:
        if (htm.indexOf('a href')) {
          return convertlink(htm);
        } else {
          if (/^\d+$/.test(htm)) {
            return parseInt(htm);
          } else {
            return clearentity(htm);
          }
        }
      }
    }
    function yearc(d){
      var date;
      d = replace$.call(d.replace(/年度|月/g, '/'), /日/, '');
      date = d.split('/');
      date[0] = parseInt(date[0]) + 1911;
      return date.join('/');
    }
    function yearrange(d){
      d = d.replace(/^到|到$/, '');
      if (d.match('到')) {
        d = d.split('到');
        if (d[0] != null) {
          d[0] = yearc(d[0]);
        }
        if (d[1] != null) {
          d[1] = yearc(d[1]);
        }
        return join$.call(d, '~');
      } else {
        return yearc(d);
      }
    }
    function clearhtm(h){
      h = replace$.call(h, /<\/?[^>+]>/gm, '');
      return clearentity(h);
    }
    function clearentity(h){
      return replace$.call(h, /&.{0,}?;/gm, '');
    }
    function convertlink(h){
      var $, links, i$, len$, a, href;
      $ = cheerio.load(h);
      links = $('a');
      for (i$ = 0, len$ = links.length; i$ < len$; ++i$) {
        a = links[i$];
        href = $(a).attr('href').replace(/^\.\.\//, 'http://donate.mohw.gov.tw/');
        $(a).attr('href', href);
      }
      return $.html();
    }
    function grabl(s){
      var b;
      if (s != null) {
        b = fs.readFileSync('debug2.htm', 'utf-8');
      } else {
        b = fs.readFileSync('debug.htm', 'utf-8');
      }
      return cheerio.load(b);
    }
    return grabl;
  });
}).call(this);
